title: Sean Su
name: Sean Su
email: seansu@me.com 
location: British Columbia, Canada
description: Sean Su
baseurl: ""
url: "https://rasen-m.github.io/"

twitter: rasen-m
github: rasen-m
linkedin: sean-su

# Build settings
markdown: kramdown
# theme: minima
  # - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock