title: Sean Su
name: Sean Su
email: seansu@me.com 
location: Vancouver, Canada
description: >
  Sean Su
baseurl: ""
url: "https://kasaobake.github.io/"

twitter: kasa0bake
github: kasaobake
linkedin: sean-su

# Build settings
markdown: kramdown
# theme: minima
  # - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
