title: 19
name: Sean Su
email: itsykumo@gmail.com 
location: Vancouver, Canada
description: >
  Sean Su
baseurl: "/"
url: "https://itsykumo.github.io/"

twitter: itsykumo
github: itsykumo
linkedin: sean-su

# Build settings
markdown: kramdown
# theme: minima
  # - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock